version: "3.8"
services:
    app:
        image: REPLACE_IMAGE_NAME_HERE
        restart: unless-stopped
        networks:
            server-internal:
                ipv4_address: 172.128.1.1
        volumes:
            - "/opt/hermes/data/pg:/var/lib/postgresql/data"
            - "/opt/hermes/data/storage/app:/srv/www/storage/app"
