version: '3.8'
services:
    app:
        image: REPLACE_IMAGE_NAME_HERE
        restart: unless-stopped
        networks:
            hermes:
                ipv4_address: 172.128.0.1
        volumes:
            - '/opt/hermes/data/pg:/var/lib/postgresql/data'

    nginx-proxy-manager:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        volumes:
            - ./data:/nginx-proxy-manager/data
            - ./letsencrypt:/nginx-proxy-manager/data
        networks:
            hermes:
                ipv4_address: 172.128.0.2

networks:
    hermes:
        driver: bridge
        ipam:
            config:
                -   subnet: 172.128.0.0/16